apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-lab-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
